# Generated by Django 5.0.14 on 2026-09-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(choices=[('energy', 'Energy'), ('power', 'Power')], default='power', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('voltage_level', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=255, unique=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PlantNameAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255, unique=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ingestion.powerplant')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255, unique=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('producer_type', models.CharField(blank=True, max_length=50)),
                ('unit_capacity_spec', models.CharField(blank=True, max_length=100)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='ingestion.powerplant')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='raw_reports/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingestion.organization')),
            ],
            options={
                'unique_together': {('organization', 'report_date', 'original_filename')},
            },
        ),
        migrations.CreateModel(
            name='SystemSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('day_peak_generation_mw', models.FloatField(blank=True, null=True)),
                ('day_peak_generation_time', models.TimeField(blank=True, null=True)),
                ('day_peak_demand_mw', models.FloatField(blank=True, null=True)),
                ('day_peak_demand_time', models.TimeField(blank=True, null=True)),
                ('evening_peak_generation_mw', models.FloatField(blank=True, null=True)),
                ('evening_peak_generation_time', models.TimeField(blank=True, null=True)),
                ('evening_peak_demand_mw', models.FloatField(blank=True, null=True)),
                ('evening_peak_demand_time', models.TimeField(blank=True, null=True)),
                ('min_generation_mw', models.FloatField(blank=True, null=True)),
                ('min_generation_time', models.TimeField(blank=True, null=True)),
                ('max_generation_mw', models.FloatField(blank=True, null=True)),
                ('max_generation_time', models.TimeField(blank=True, null=True)),
                ('energy_generated_mkwh', models.FloatField(blank=True, null=True)),
                ('energy_unserved_mkwh', models.FloatField(blank=True, null=True)),
                ('energy_demand_mkwh', models.FloatField(blank=True, null=True)),
                ('max_temperature_c', models.FloatField(blank=True, null=True)),
                ('total_gas_supplied_mmcfd', models.FloatField(blank=True, null=True)),
                ('production_cost_per_kwh_tk', models.FloatField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_summary', to='ingestion.reportsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('zone', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=50)),
                ('energy_mkwh', models.FloatField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_generation', to='ingestion.reportsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='FuelSourceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('time', models.CharField(max_length=5)),
                ('source', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('domestic_generation', 'Domestic generation'), ('imported_power', 'Imported power'), ('shortage', 'Shortage')], max_length=30)),
                ('value_mw', models.FloatField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_source_readings', to='ingestion.reportsubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['report_date', 'source'], name='ingestion_f_report__341848_idx')],
            },
        ),
        migrations.CreateModel(
            name='StagingCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=100)),
                ('row_number', models.IntegerField()),
                ('column_name', models.CharField(max_length=255)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_cells', to='ingestion.reportsubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['submission', 'sheet_name'], name='ingestion_s_submiss_287ffd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('hour', models.TimeField()),
                ('generation_mw', models.FloatField(blank=True, null=True)),
                ('load_shed_mw', models.FloatField(blank=True, null=True)),
                ('demand_mw', models.FloatField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_hourly', to='ingestion.reportsubmission')),
            ],
            options={
                'unique_together': {('report_date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='UnitGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('hour', models.TimeField(blank=True, null=True)),
                ('reading_type', models.CharField(choices=[('actual_hourly', 'Actual (hourly, GenLog)'), ('actual_day_peak', 'Actual — day peak (prior day)'), ('actual_evening_peak', 'Actual — evening peak (prior day)'), ('forecast_day_peak', 'Forecast — day peak'), ('forecast_evening_peak', 'Forecast — evening peak'), ('effective_day_peak', 'Effective available — day peak'), ('effective_evening_peak', 'Effective available — evening peak'), ('peak_hour', 'Peak hour generation (P2)'), ('energy_generated_kwh', 'Energy generated, day-long (P2)')], max_length=30)),
                ('generation_mw', models.FloatField(blank=True, null=True)),
                ('installed_capacity_mw', models.FloatField(blank=True, null=True)),
                ('present_capacity_mw', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_generation', to='ingestion.reportsubmission')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='ingestion.generatingunit')),
            ],
            options={
                'indexes': [models.Index(fields=['unit', 'report_date', 'reading_type'], name='ingestion_u_unit_id_567c54_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoltageReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('max_voltage_kv', models.FloatField(blank=True, null=True)),
                ('max_voltage_time', models.TimeField(blank=True, null=True)),
                ('min_voltage_kv', models.FloatField(blank=True, null=True)),
                ('min_voltage_time', models.TimeField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voltage_readings', to='ingestion.reportsubmission')),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='ingestion.substation')),
            ],
            options={
                'unique_together': {('substation', 'report_date')},
            },
        ),
    ]
